### ISSUE TITLE
Intégrer une fonction de  liste blanche

### ISSUE THREAD

**Issue by IssouLinux** [Rand0max/deboucled#20]
Bonjour les kheys spé dev,

Serait-il possible d'ajouter au script une fonctionnalité de liste blanche?  Car je remarque à la longue qu'il  y a des kheys dont j'aimerai bien voir les messages et topics mais il se trouve malheureusement qu'ils ont été ajouté à une liste antiboucle.

**Comment by Rand0max** [comment]
Salut clé, merci pour la suggestion c'est déjà planifié : https://github.com/Rand0max/deboucled/issues/9
En attendant tu peux décocher l'option "Masquer totalement les messages des pseudos blacklists" pour qu'ils apparaissent.
